services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:7860" # Map host 8000 -> container 7860
    env_file:
      - .env
    environment:
      - PORT=7860

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - PORT=3000
      - HOSTNAME=0.0.0.0
    depends_on:
      - backend